# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.25.0
import dataclasses
from typing import Any, Optional


@dataclasses.dataclass()
class Author:
    id: Any
    name: Any
    bio: Optional[Any]
